mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.username=elysesherwin@gmail.com
mail.password=tqpw fmzt gjwd tbux
mail.from=elysesherwin@gmail.com
